config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  resources :articles do
    resources :comments
  end
  
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="fadeInUp">
      <h2 class="text-warning">
        <%= pluralize(@article.errors.count, "error") %> prohibited 
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group fadeInUp">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Article title", autocomplete: "off", :class => 'form-control p-3 shadow-sm' %>
  </div>

  <div class="form-group fadeInUp">
    <%= form.label :content %>
    <%= form.text_area :text, :rows => '10', placeholder: "Write some content...", :class => 'form-control p-3 shadow-sm' %>
  </div>

  <div class="form-group fadeInUp">
    <%= form.submit :class => 'btn btn-outline-primary' %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div class="container py-5">
  <%= link_to '× Cancel', articles_path, :class => 'btn btn-outline-danger mb-4 close' %>
  <h1 class="pb-4">Edit: <span class="font-weight-light"><%= @article.title %></span></h1>

  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container py-5">
  <h1 class="pb-4">Blog</h1>

  <%= link_to 'New article', new_article_path, :class => 'btn btn-sm btn-link text-hover-primary' %>

  <% @articles.each do |article| %>
    <article class="card my-5 shadow-sm article fadeInUp">
      <div class="card-body">
          <h5 class="card-title article-title">
            <%= link_to article.title, article_path(article) %>
          </h5>
          <!---->
          <p class="card-text article-text">
            <%= article.text %>
          </p>
          <p class="card-text text-right">
            <%= link_to 'View', article_path(article), :class => 'btn btn-sm btn-link' %>
            <%= link_to 'Edit', edit_article_path(article), :class => 'btn btn-sm btn btn-link text-hover-info mx-2' %>
            <%= link_to 'Delete', article_path(article),
                    :class => 'btn btn-sm btn-link text-hover-danger',
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
          </p>
      </div>
    </article>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container py-5" id="new">
  <%= link_to '× Cancel', articles_path, :class => 'btn btn-outline-danger mb-4 close' %>
  <h1 class="pb-4">New Article</h1>

  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <article class="py-5" id="article-full">
    <%= link_to '❮ Back', articles_path, :class => 'btn btn-link mr-2' %>
    <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn btn-link text-hover-info float-right mx-2' %>

    <h1 class="py-4 article-title"><%= @article.title %></h1>

    <div class="card mb-4 shadow-sm fadeInUp">
      <div class="card-body">
        <p class="card-text">
          <%= @article.text %>
        </p>
      </div>
    </div>

    <hr class="my-5 fadeInUp"/>

    <h4 class="mb-4 text-white fadeInUp">Comments</h4>
    <%= render @article.comments %>

    <h5 class="mt-5 mb-4 pt-4 text-white fadeInUp">Add a comment</h5>
    <%= render 'comments/form' %>
  </article>
</div>

app/views/comments/_comment.html.erb
<div class="card shadow-sm fadeInUp">
  <div class="card-body">
    <p class="card-text">
      <%# <strong>Name:</strong> %>
      <span class="font-weight-bold comments-name">
        <%= comment.commenter %>
      </span>
    </p>
    <p class="card-text">
      <%# <strong>Comment:</strong> %>
      <blockquote class="blockquote border-left pl-3 comments-body">
        <%= comment.body %>
      </blockquote>
    </p>

    <p class="card-text">
      <%= link_to 'Delete Comment', [comment.article, comment],
                  :class => 'btn btn-sm btn-link text-hover-danger delete',
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <div class="fadeInUp">
    <div class="form-group w-25" id="comment-name">
      <%= form.label :name %>
      <%= form.text_field :commenter, placeholder: "Johnny Appleseed", autocomplete: "off", :class => 'form-control shadow-sm' %>
    </div>

    <div class="form-group w-75 mb-3" id="comment-body">
      <%= form.label :comment %>
      <%= form.text_area :body, :rows => '3', placeholder: "Write some content...", :class => 'form-control shadow-sm' %>
    </div>

    <%= form.submit 'Submit Comment', :class => 'btn btn-outline-primary mt-1' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="github fadeIn">
      <a href="https://github.com/derekbtw/rails-dark-blog" target="_blank">
        <svg height="32" class="octicon octicon-mark-github" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
      </a>
    </div>
    <%= yield %>
    <div class="container">
      <div class="col">
        <p class="text-center fadeIn text-white-50 font-weight-light py-4">
          &copy; 2018 Derek Bytheway
        </p>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>